### ISSUE TITLE
f1问题

### ISSUE THREAD

**Issue by Victor-xx** [sxysxy/NERTasks#1]
您好，后面全是{'loss': 28.06040613539517, 'time_sec': 70.36982, 'f1': 0.0, 'accuracy': 0.8383486885472077}，loss下降f1一直是0，还有就是batch size为啥设为1捏

**Comment by sxysxy** [comment]
F1变为0我印象里是我也触发过这个问题的，但是不太记得了，您可以说一下您用哪个模型？哪个数据集嘛？batch_size设置为1但是我用了梯度累积，实际等效的batch_size要乘以梯度累积数。设置为1是因为两方面原因，一个是我使用的CRF层是我自己写的，由于水平有限，写不出来batched版本，一次只能处理一个样本。其实可以用torch-struct提供的CRF，他支持batched输入。另一个原因是我用到的模型里还包括了纯RNN的模型，在我的实验中发现，如果增大batch_size，需要对文本做padding，pad token的出现似乎对基于RNN的NER模型的负面影响很大，我增大batch_size并在后面padding补齐之后，F1非常低。而一个一个喂进去样本就好了，然后用梯度累积来实现等效的mini-batch的梯度下降。关于为什么padding补了之后对效果影响非常大我也一直想知道。

**Comment by Victor-xx** [comment]
我就简单跑了ccks2019数据集的BERT-BiLSTM-Linear和BERT-BiLSTM-Linear-crf

**Comment by sxysxy** [comment]
我看了一下当初ccks2019上我没有跑BERT-BiLSTM-Linear的模型，BERT-BiLSTM-Linear-CRF的模型有，生成的结果文件是这个： https://github.com/sxysxy/NERTasks/blob/main/reference_results/ccks2019-BERT-Linear-CRF-2022-05-03-23-58-34.json 参考这个文件的结果，首先几轮的F1确实是0，训练几轮之后才提升起来。可以多训练几轮再看看，同理BERT-BiLSTM-Linear也是

**Comment by sxysxy** [comment]
另外也可能会因为BERT-BiLSTM-Linear这个模型太深了，我的训练技巧也比较naive，超参数也不是很好，有可能会一直支棱不起来

**Comment by Victor-xx** [comment]
好的谢谢您
